music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    #index music
    url(r'^$',views.indexView.as_view(),name='index'),
    #music by id
    url(r'^(?P<pk>[0-9]+)/$', views.detailView.as_view(), name='detail'),
    url(r'hello/$', views.hello.as_view(), name='hello'),
    #add album
    url(r'^album/add/$', views.albumCreate.as_view() , name='Album-add'),
    url(r'album/(?P<pk>[0-9]+)/$', views.albumUpdate.as_view() , name='Album-update'),
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.albumDelete.as_view() , name='Album-delete'),
]

#old
"""
    urlpatterns = [
        #index music
        url(r'^$',views.index,name='index'),
        #music by id
        url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
        #music by id / favorite
        url(r'^(?P<album_id>[0-9]+)/favorite$', views.favorite, name='favorite'),
    ]
"""

website/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

music/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=250)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def get_absolute_url(self):
        return reverse('music:detail',kwargs={'pk':self.pk})

    def __str__(self):
        return self.album_title + ' - ' + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album,on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title =  models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)
    def __str__(self):
        return self.song_title

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView , UpdateView , DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Album


class indexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'
    def get_queryset(self):
        return Album.objects.all()

class detailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'


class albumCreate(CreateView):
    model = Album
    fields = ['artist','album_title','genre','album_logo']

class albumUpdate(UpdateView):
    model = Album
    fields = ['artist','album_title','genre','album_logo']

class albumDelete(DeleteView):
    model = Album
    succes_url = reverse_lazy('music:index')

class hello(generic.DetailView):
    template_name = 'music/hello.html'










"""
def index(request):
    all_albums = Album.objects.all()
    template = loader.get_template('music/index.html')
    context = { 'all_albums' : all_albums}
    return HttpResponse(template.render(context,request))
"""

"""
def detail(request,album_id):
    try:
        album = Album.objects.get(pk=album_id)
    except Album.DoesNotExist:
        raise Http404("Album does not exist")
    context = { 'album' : album}
    return render(request,'music/detail.html',context)
"""


# version non bootstrap
"""
from django.shortcuts import render , get_object_or_404
from .models import Album
#from django.http import Http404

    def index(request):
    all_albums = Album.objects.all()
    #context = { 'all_albums' : all_albums}
    #return render(request,'music/index.html',context)
    return render(request,'music/index.html',{'all_albums' : all_albums})

def detail(request,album_id):
    #    album = Album.objects.get(pk=album_id)
    # get_object_or_404(Model,id)
    album = get_object_or_404(Album,pk=album_id)
    return render(request,'music/detail.html',{'album' : album})

def favorite(request, album_id):
    album = get_object_or_404(Album,pk=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])
    except(KeyError, Song.DoesNotExist):
        return render(request,'music/detail.html',{
            'album' : album,
            'error_message' : "You did not select a valid song"
        })
    else:
        selected_song.is_favorite = True
        selected_song.save()
        return render(request,'music/detail.html',{'album' : album})
"""

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block album_active %}active{% endblock %}

{% block isi %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include 'music/form-template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    <div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Music{% endblock %}</title>

    {% load staticfiles %}
    <link rel="stylesheet" type="text/css"  href="{% static 'music/css/style.css' %}" />
    <link rel="stylesheet" type="text/css"  href="{% static 'music/fonts/font-satisfy.css' %}" />
    <link rel="stylesheet" type="text/css"  href="{% static 'music/css/bootstrap.min.css' %}" />
    <script src="{% static 'music/js/jquery.min.js' %}"></script>
    <script src="{% static 'music/js/bootstrap.min.js' %}"></script>

</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'music:index' %}">MUSIC</a>      
            </div>

            <!-- item -->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'music:index' %}">
                            <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp
                            Albums
                        </a>
                    <li>
                    <li class="">
                        <a href="{% url 'music:index' %}">
                            <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp
                            Songs
                        </a>
                    <li>
                </ul>

                <form class="navbar-form navbar-left" role="search" method="GET" action="#">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" value="">
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form>

                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'music:Album-add' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp
                            Add Album
                        </a>
                    <li>
                    <li class="">
                        <a href="{% url 'music:index' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp
                            Logout
                        </a>
                    <li>
                </ul>
            </div>
        </div>
    </nav>
    {% block isi %}
    {% endblock %}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Album Detail{% endblock %}


{% block isi %}
    <img src="{{ album.album_logo}}" width="200px">

    <h1>{{ album.album_title }}</h1>
    <h2>{{ album.artist }}</h2>

    {% if error_message %}
      <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    <form action="" method="POST">
      {% csrf_token %}
      {% for song in album.song_set.all %}
          <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}"/>
          <label for="song{{ forloop.counter }}">
              {{ song.song_title }}
              {% if song.is_favorite %}
                <img src="http://i.imgur.com/b9b13Rd.png" />
              {% endif %}
          </label><br>
      {% endfor %}
        <input type="submit" value="favorite" />
    </form>
{% endblock %}



<!--
<ul>
    {% for song in album.song_set.all %}
      <li>{{ song.song_title }}.{{ song.file_type }}</li>
    {% endfor %}
</ul> -->

music/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">           
           <span class="text-danger small">{{field.error}}</span>
        </div>
        <label class="control-label col-sm-2">{{field.label_tag}}</label>
        <div class="col-sm10">{{field}}</div>
     <div>
{% endfor %}

music/templates/music/hello.html
<p> hello</p>

music/templates/music/index.html
{% extends 'music/base.html' %}
{% block albums_active %}active{% endblock %}

{% block isi %}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <!--<h3>{{ user.username }}'s Albums</h3> -->
        </div>
        {% if all_albums %}
            {% for album in all_albums %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'music:detail' album.id %}">
                            <img src="{{ album.album_logo }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ album.album_title }}</h2>
                            <h4>{{ album.artist }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="{% url 'music:Album-delete' album.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'music:Album-add' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                    </button>
                </a>
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}






